namespace java com.didiglobal.thrift.original

struct Items {
    1:required list<Item> cards;
}

struct Item {
    1:required i64 activityId;
    2:required string image;
    3:required string link;
    4:required string title;
    5:required list<string> contents;
}

service Original {
    Items getActivityCards ();
}