namespace java com.didiglobal.thrift.sample1.samplenew

struct Items{
     1:required i64 id;
     2:required list<Item> items;
}
struct Item {
    1:required string name;
    2:required string image;
    3:required list<string> contents;
}

service Sample {
    Items getItems(1:i64 id);
}