/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.didiglobal.thrift.sampleold;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2019-06-06")
public class CardsReqInfo implements org.apache.thrift.TBase<CardsReqInfo, CardsReqInfo._Fields>, java.io.Serializable, Cloneable, Comparable<CardsReqInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CardsReqInfo");

  private static final org.apache.thrift.protocol.TField DRIVER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("driverId", org.apache.thrift.protocol.TType.I64, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CardsReqInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CardsReqInfoTupleSchemeFactory();

  public long driverId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DRIVER_ID((short)1, "driverId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DRIVER_ID
          return DRIVER_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DRIVERID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DRIVER_ID, new org.apache.thrift.meta_data.FieldMetaData("driverId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CardsReqInfo.class, metaDataMap);
  }

  public CardsReqInfo() {
  }

  public CardsReqInfo(
    long driverId)
  {
    this();
    this.driverId = driverId;
    setDriverIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CardsReqInfo(CardsReqInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.driverId = other.driverId;
  }

  public CardsReqInfo deepCopy() {
    return new CardsReqInfo(this);
  }

  @Override
  public void clear() {
    setDriverIdIsSet(false);
    this.driverId = 0;
  }

  public long getDriverId() {
    return this.driverId;
  }

  public CardsReqInfo setDriverId(long driverId) {
    this.driverId = driverId;
    setDriverIdIsSet(true);
    return this;
  }

  public void unsetDriverId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DRIVERID_ISSET_ID);
  }

  /** Returns true if field driverId is set (has been assigned a value) and false otherwise */
  public boolean isSetDriverId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DRIVERID_ISSET_ID);
  }

  public void setDriverIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DRIVERID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case DRIVER_ID:
      if (value == null) {
        unsetDriverId();
      } else {
        setDriverId((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DRIVER_ID:
      return getDriverId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DRIVER_ID:
      return isSetDriverId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof CardsReqInfo)
      return this.equals((CardsReqInfo)that);
    return false;
  }

  public boolean equals(CardsReqInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_driverId = true;
    boolean that_present_driverId = true;
    if (this_present_driverId || that_present_driverId) {
      if (!(this_present_driverId && that_present_driverId))
        return false;
      if (this.driverId != that.driverId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(driverId);

    return hashCode;
  }

  @Override
  public int compareTo(CardsReqInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetDriverId()).compareTo(other.isSetDriverId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDriverId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.driverId, other.driverId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CardsReqInfo(");
    boolean first = true;

    sb.append("driverId:");
    sb.append(this.driverId);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'driverId' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CardsReqInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CardsReqInfoStandardScheme getScheme() {
      return new CardsReqInfoStandardScheme();
    }
  }

  private static class CardsReqInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<CardsReqInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CardsReqInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DRIVER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.driverId = iprot.readI64();
              struct.setDriverIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetDriverId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'driverId' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CardsReqInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(DRIVER_ID_FIELD_DESC);
      oprot.writeI64(struct.driverId);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CardsReqInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CardsReqInfoTupleScheme getScheme() {
      return new CardsReqInfoTupleScheme();
    }
  }

  private static class CardsReqInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<CardsReqInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CardsReqInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI64(struct.driverId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CardsReqInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.driverId = iprot.readI64();
      struct.setDriverIdIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

